version: '3.8'

services:
  # ─── Postgres ───────────────────────────────────────────────────────
  posthog-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: posthog
      POSTGRES_DB: posthog

  # ─── Redis ─────────────────────────────────────────────────────────
  posthog-redis:
    image: redis:6
    restart: always

  # ─── ZooKeeper (for Kafka) ─────────────────────────────────────────
  posthog-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ─── Kafka ──────────────────────────────────────────────────────────
  posthog-kafka:
    image: confluentinc/cp-kafka:7.0.1
    restart: always
    depends_on:
      - posthog-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: posthog-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://posthog-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ─── ClickHouse ─────────────────────────────────────────────────────
  posthog-clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # ─── PostHog Web ────────────────────────────────────────────────────
  posthog:
    image: posthog/posthog:latest
    restart: always
    depends_on:
      - posthog-db
      - posthog-redis
      - posthog-zookeeper
      - posthog-kafka
      - posthog-clickhouse
    ports:
      - "8000:8000"
    environment:
      # the URL you’ll use in your browser
      SITE_URL: http://localhost:8000

      # point at the Postgres database
      DATABASE_URL: postgresql://posthog:posthog@posthog-db:5432/posthog

      # point at Redis
      REDIS_URL: redis://posthog-redis:6379/0

      # enable Kafka event queueing
      KAFKA_BOOTSTRAP_SERVERS: posthog-kafka:9092

      # point at your ClickHouse instance
      CLICKHOUSE_HOST: posthog-clickhouse

      # ensure PostHog migrations run on startup
      DJANGO_SETTINGS_MODULE: posthog.settings

networks:
  default:
    name: posthog-selfhost-network