posthog:
  image: posthog/posthog:latest
  restart: always
  depends_on:
    - posthog-db
    - posthog-redis
    - posthog-zookeeper
    - posthog-kafka
    - posthog-clickhouse
  ports:
    - "8000:8000"
  environment:
    SITE_URL: http://localhost:8000
    DATABASE_URL: postgresql://posthog:posthog@posthog-db:5432/posthog
    REDIS_URL: redis://posthog-redis:6379/0
    KAFKA_BOOTSTRAP_SERVERS: posthog-kafka:9092
    CLICKHOUSE_HOST: posthog-clickhouse
    DJANGO_SETTINGS_MODULE: posthog.settings
    SECRET_KEY: "8afd95be962e48db7306a2c17bb0d2bb47f57aba12b374063e45d6e5f63f898a"
