services:
  # ─── Postgres ───────────────────────────────────────────────────────
  posthog-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: posthog
      POSTGRES_PASSWORD: posthog
      POSTGRES_DB: posthog

  # ─── Redis ─────────────────────────────────────────────────────────
  posthog-redis:
    image: redis:6
    restart: always

  # ─── ZooKeeper (for Kafka) ─────────────────────────────────────────
  posthog-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    platform: linux/amd64
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ─── Kafka ──────────────────────────────────────────────────────────
  posthog-kafka:
    image: confluentinc/cp-kafka:7.0.1
    platform: linux/amd64
    restart: always
    depends_on:
      - posthog-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: posthog-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://posthog-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ─── ClickHouse ─────────────────────────────────────────────────────
  posthog-clickhouse:
    image: clickhouse/clickhouse-server:latest
    platform: linux/amd64
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # ─── PostHog Web ────────────────────────────────────────────────────
  posthog:
    image: posthog/posthog:latest
    platform: linux/amd64
    restart: always
    depends_on:
      - posthog-db
      - posthog-redis
      - posthog-zookeeper
      - posthog-kafka
      - posthog-clickhouse
    ports:
      - "8000:8000"
    environment:
      SITE_URL: http://localhost:8000
      DATABASE_URL: postgresql://posthog:posthog@posthog-db:5432/posthog
      REDIS_URL: redis://posthog-redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: posthog-kafka:9092
      CLICKHOUSE_HOST: posthog-clickhouse
      DJANGO_SETTINGS_MODULE: posthog.settings
      SECRET_KEY: "8afd95be962e48db7306a2c17bb0d2bb47f57aba12b374063e45d6e5f63f898a"

volumes:
  posthog-db:
  posthog-redis:
